undo auto-formatting

diff --git a/cpuvinf b/cpuvinf
--- a/cpuvinf
+++ b/cpuvinf
@@ -15,13 +15,13 @@
 # in /opt/vc/bin on a 64-bit system. An appropriate one is probably in /usr/bin.
 _vcgencmd=$( command -v vcgencmd )
 if [ -z "$_vcgencmd" ] || ! $_vcgencmd commands >/dev/null 2>&1; then
-  echo -e "\x1b[31mcpuvinf: error: unable to execute vcgencmd; please check your configuration\x1b[0m"
-  exit 1
+   echo -e "\x1b[31mcpuvinf: error: unable to execute vcgencmd; please check your configuration\x1b[0m"
+   exit 1
 fi
 
 # Current CPU/GPU temperatures in Celsius and Fa-
 # renheit
-temp ()  {
+temp ()	{
    tempc=$( awk '{printf "%3.1f°C\n", $1/1000}' /sys/class/thermal/thermal_zone0/temp )
    tempf=$( awk '{printf "%3.1f°F\n", $1/1000*9/5+32}' /sys/class/thermal/thermal_zone0/temp )
    echo ""
@@ -55,7 +55,7 @@ clock () {
 }
 
 # System voltages in Volt (Core, SDRAM, etc...)
-volt ()  {
+volt () {
    vcore=$( $_vcgencmd measure_volts core | sed 's/volt=//' )
    vsdramcore=$( $_vcgencmd measure_volts sdram_c | sed 's/volt=//' )
    vsdramio=$( $_vcgencmd measure_volts sdram_i | sed 's/volt=//' )
@@ -72,7 +72,7 @@ volt ()  {
 
 # Memorysplit for system usable RAM and GPU
 # usable RAM
-memorysplit () {
+memorysplit ()	{
    systemram=$( $_vcgencmd get_mem arm | sed -r 's/^.{4}//' )
    gpuram=$( $_vcgencmd get_mem gpu | sed -r 's/^.{4}//')
    echo ""
@@ -84,52 +84,52 @@ memorysplit () {
 }
 
 # Help
-help ()  {
-   echo ""
-   echo "cpuvinf 1.3 by Hidden Refuge <me at hiddenrefuge dot eu dot org>"
-   echo ""
-    echo "Usage: cpuvinf <option>"
-   echo ""
-   echo "Available options:"
-   echo "-t, --temperature Displays CPU/GPU temperature in °C/°F."
-   echo "-c, --clocks      Displays CPU/GPU clocks in MHz and CPU governor."
-   echo "-v, --voltages    Displays voltages of the core and SDRAM."
-   echo "-m, --memory      Displays the assigned memory amount for the GPU and the system."
-   echo "-a, --all      Displays all the things above at once."
-   echo ""
-   echo "Unfortunately CPUVInf has no man page :("
-   echo ""
+help ()	{
+	echo ""
+	echo "cpuvinf 1.3 by Hidden Refuge <me at hiddenrefuge dot eu dot org>"
+	echo ""
+   echo "Usage: cpuvinf <option>"
+	echo ""
+	echo "Available options:"
+	echo "-t, --temperature	Displays CPU/GPU temperature in °C/°F."
+	echo "-c, --clocks		Displays CPU/GPU clocks in MHz and CPU governor."
+	echo "-v, --voltages		Displays voltages of the core and SDRAM."
+	echo "-m, --memory		Displays the assigned memory amount for the GPU and the system."
+	echo "-a, --all		Displays all the things above at once."
+	echo ""
+	echo "Unfortunately CPUVInf has no man page :("
+	echo ""
 }
 
 # Option selection (short and long parameters)
 case $1 in
     '-t')
-         temp;;
-   '--temperature')
-      temp;;
-   '-c')
-      clock;;
-   '--clocks')
-      clock;;
+       	temp;;
+	'--temperature')
+		temp;;
+	'-c')
+		clock;;
+	'--clocks')
+		clock;;
     '-v')
         volt;;
-   '--voltages')
-      volt;;
-   '-m')
-      memorysplit;;
-   '--memory')
-      memorysplit;;
-   '-a')
-      temp; clock; volt; memorysplit;;
-   '--all')
-      temp; clock; volt; memorysplit;;
-   '-h')
-      help;;
+	'--voltages')
+		volt;;
+	'-m')
+		memorysplit;;
+	'--memory')
+		memorysplit;;
+	'-a')
+		temp; clock; volt; memorysplit;;
+	'--all')
+		temp; clock; volt; memorysplit;;
+	'-h')
+		help;;
     '--help')
-      help;;
-   *)
-      echo ""
-      echo "cpuvinf: Empty or invalid option!"
-      echo "Try 'cpuvinf -h' or 'cpuvinf --help' for more information."
-      echo "";;
+		help;;
+	*)
+		echo ""
+		echo "cpuvinf: Empty or invalid option!"
+		echo "Try 'cpuvinf -h' or 'cpuvinf --help' for more information."
+		echo "";;
 esac
